SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS PURCHASE;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS PRODUCT;




/* Create Tables */

-- 회원
CREATE TABLE MEMBER
(
	MEMBER_SEQ varchar(60) NOT NULL,
	MEMBER_ID varchar(20),
	MEMBER_PASS varchar(30),
	MEMBER_NAME varchar(10),
	MEMBER_PHONE varchar(20),
	-- 탈퇴한 회원인지 아닌지 구분하기 위함
	MEMBER_STATUS varchar(2),
	MEMBER_AUT varchar(20),
	PRIMARY KEY (MEMBER_SEQ)
);


-- 상품
CREATE TABLE PRODUCT
(
	PRODUCT_SEQ varchar(60) NOT NULL,
	PRODUCT_NAME varchar(30),
	PRODUCT_PRICE int,
	PRODUCT_EXP varchar(2000),
	PRODUCT_STOCK int,
	PRODUCT_IMAGE varchar(2000),
	PRIMARY KEY (PRODUCT_SEQ)
);


-- 구매
CREATE TABLE PURCHASE
(
	MEMBER_SEQ varchar(60) NOT NULL,
	PRODUCT_SEQ varchar(60) NOT NULL,
);



/* Create Foreign Keys */

ALTER TABLE PURCHASE
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES MEMBER (MEMBER_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PURCHASE
	ADD FOREIGN KEY (PRODUCT_SEQ)
	REFERENCES PRODUCT (PRODUCT_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



